title = "sys_config"

# API
[api.durian]
ip = "10.251.31.143"
host = "bb.dev.d2"
port = "80"

# DRD API
[api.drd]
ip = "drd-slot-receipt-system"
host = "drd-slot-receipt-system"
port = "80"
auth = "FcB75fjfkBKIqOrol8iBBy4lScMR7u4dY1bkt1OpXZst4u15At"

[api.jackpot]
ip = "127.0.0.1"
host = "127.0.0.1"
port = "8000"
auth = "jackpot_auth"

# RD3 API
[api.rd3]
ip = "43.251.76.232"
host = ""
port = "80"

[[server]]
name = "pepper"
port = "8501"
address = "localhost"
api_key = ""
secure = false

[web]
port = "9453"

# DB
[db]
user = "root"
pass = "qwe123"
connMaxLifetime = 180

[db.SLOT_TOOL.M]
ip = "127.0.0.1"
host = ""
port = "3306"
dbName = "SLOT_TOOL"

[db.SLOT_GAME.M]
ip = "127.0.0.1"
host = ""
port = "3306"
dbName = "SLOT_GAME"

# Url
[url]
ws = "127.0.0.1:9453/starfruit/api"
source = "storage.googleapis.com/slot-game-test"
localSource = "127.0.0.1:9453/starfruit/slot"
localPic = "127.0.0.1:9453/starfruit"
InURL = "http://d-api.inslotx.com/elibomApi/WebService/"

# Host白名單
[allow.host]
host1 = "127.0.0.1:9453"
host2 = "localhost:9453"

#彩金開關
[jackpot]
switch = false