title = "sys_config"

# # API
# [api.durian]
# ip = "10.251.37.101"
# host = "bb.dev.d2"
# port = "80"

[api.drd]
# ip = "drd-slot-receipt-system"
# host = "drd-slot-receipt-system"
# port = "80"
# auth = ""
ip = "10.108.9.31"
host = "10.108.9.31"
port = "20300"
auth = ""

# [redis.master]
# ip = "127.0.0.1"
# host = "redis-slot-game-master"
# port = "6379"

# [redis.slave]
# ip = "127.0.0.1"
# host = "redis-slot-game-slave"
# port = "6379"

[web]
port = "9453"

# DB
[db]
user = "slot-test-admin"
pass = "qwe123"
connMaxLifetime = 60

[db.SLOT_TOOL.M]
ip = "10.101.6.5"
host = "10.101.6.5"
port = "3306"
dbName = "SLOT_TOOL"

[db.SLOT_GAME.M]
ip = "10.101.6.5"
host = "10.101.6.5"
port = "3306"
dbName = "SLOT_GAME"

# MongoDB
[mdb]
ip = "10.101.6.9"
port = "27017"

# Url
[url]
ws = "in-slot-star.vir999.com/starfruit/api"
source = "sin-slot-storage.vir999.com"
localSource = "on-game-qa.in-slot.com"
localPic = "/starfruit"
InURL = "http://q-api.inslotx.com/elibomApi/WebService/"

# Host白名單
[allow.host]
host1 = "star.hadakakushi.tw"
host2 = "starfruit"
host3 = "starfruit-random-internal"
