title = "sys_config"

# # API
# [api.durian]
# ip = "10.251.37.101"
# host = "bb.dev.d2"
# port = "80"

[api.drd]
ip = "drd-slot-receipt-system"
host = "drd-slot-receipt-system"
port = "80"
auth = "FcB75fjfkBKIqOrol8iBBy4lScMR7u4dY1bkt1OpXZst4u15At"

[api.anubis]
address = "anubis"
secure = false
[[api.anubis.header]]
key = "api-key"
value = "qwe123"

[api.jackpot]
ip = "jackpot"
host = "on.jp.hadakakushi.tw"
port = "80"
auth = "jackpot_auth"

[[server]]
name = "pepper"
port = "8501"
address = "pepper-sidecar"
api_key = ""
secure = false

# Redis
[redis.master]
host = "redis-slot-game-master"
port = ":6379"
password = ""


[web]
port = "9453"

# DB
[db]
user = "slot-dev-admin"
pass = "qwe123"
connMaxLifetime = 60

[db.SLOT_TOOL.M]
ip = "mysql-slot-game"
host = "mysql-slot-game"
port = "3306"
dbName = "SLOT_TOOL"

[db.SLOT_GAME.M]
ip = "mysql-slot-game"
host = "mysql-slot-game"
port = "3306"
dbName = "SLOT_GAME"

# DRD DB
[drd]
user = "rd1gcphhslot_dev"
pass = "jo4gk6ai7ul41ijo8"

[drd.INSLOT_GAME_DB.M]
ip = "drd-slot-pepper-master"
host = "drd-slot-pepper-master"
port = "3306"
dbName = "HHSLOT_GAME_DB"

# MongoDB
[mdb]
ip = "mongodb-slot-game-master"
port = "27017"

# Url
[url]
wsSlot = "star.hadakakushi.tw/starfruit/apiSlot"
wsCrush = "star.hadakakushi.tw/starfruit/apiCrush"
source = "storage.hadakakushi.tw"
localSourceSlot = "star.hadakakushi.tw/starfruit/slot"
localSourceCrush = "star.hadakakushi.tw/starfruit/crush"
localPic = "star.hadakakushi.tw/starfruit"
InURL = "http://q-api.inslotx.com/elibomApi/WebService/"
betHistory = "on.ex.hadakakushi.tw/user-bet-record/#/"
gameRule = "on.ex.hadakakushi.tw/rule/#/"

# Host白名單
[allow.host]
host1 = "star.hadakakushi.tw"
host2 = "starfruit"
host3 = "starfruit-random-internal"

[api.onion]
name = "onion"
address = "on.play.hadakakushi.tw"
secure = false

#彩金開關
[jackpot]
switch = true