title = "sys_config"

# RD5 API
[api.durian]
ip = "172.17.157.26"
host = "bb.durian"
port = "80"

# RD3 API
[api.rd3]
ip = "172.17.188.26"
host = ""
port = "80"

# RD6 API
[api.rd6]
ip = ""
host = ""
port = ""


# DRD API
[api.drd]
ip = ""
host = ""
port = ""
auth = ""

# [redis.master]
# ip = "127.0.0.1"
# host = "redis-slot-game-master"
# port = "6379"

# [redis.slave]
# ip = "127.0.0.1"
# host = "redis-slot-game-slave"
# port = "6379"

[memcache]
ip = "172.17.63.31"
port = "11212"

[web]
port = "9453"

# DB
[db]
user = ""
pass = ""
connMaxLifetime = 60

[db.SLOT_TOOL.M]
ip = ""
host = ""
port = ""
dbName = ""

[db.SLOT_GAME.M]
ip = ""
host = ""
port = ""
dbName = ""

# MongoDB
[mdb]
ip = ""
port = ""

# Url
[url]
ws = "/starfruit/api"
localSource = "/starfruit/slot"
localPic = "/starfruit"
source = "in-slot-storage.vir999.com"
InURL = "http://q-api.inslotx.com/elibomApi/WebService/"

# Host白名單
[allow.host]
host1 = ""
host2 = ""
